/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyEmpMgmtApp.gui;

import MyEmpMgmtApp.dbutil.DBConnection;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class ChoiceEmp extends javax.swing.JFrame {

    /**
     * Creates new form firstPage
     */
    int xx,xy;                             
    public ChoiceEmp() {
        initComponents();
        super.setLocationRelativeTo(null);
        DBConnection.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        radioadd = new javax.swing.JRadioButton();
        radiosearch = new javax.swing.JRadioButton();
        radioshow = new javax.swing.JRadioButton();
        radioquit = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jbupdate = new javax.swing.JRadioButton();
        jrdelete = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        radioadd.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(radioadd);
        radioadd.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        radioadd.setForeground(new java.awt.Color(255, 255, 255));
        radioadd.setText("Add Employ");
        radioadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioaddActionPerformed(evt);
            }
        });

        radiosearch.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(radiosearch);
        radiosearch.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        radiosearch.setForeground(new java.awt.Color(255, 255, 255));
        radiosearch.setText("Search Employ");
        radiosearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiosearchActionPerformed(evt);
            }
        });

        radioshow.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(radioshow);
        radioshow.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        radioshow.setForeground(new java.awt.Color(255, 255, 255));
        radioshow.setText("Show all Employ");
        radioshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioshowActionPerformed(evt);
            }
        });

        radioquit.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(radioquit);
        radioquit.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        radioquit.setForeground(new java.awt.Color(255, 255, 255));
        radioquit.setText("Quit");
        radioquit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioquitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select Your Choice");

        jbupdate.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jbupdate);
        jbupdate.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jbupdate.setForeground(new java.awt.Color(255, 255, 255));
        jbupdate.setText("Update Employ Details ");
        jbupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbupdateActionPerformed(evt);
            }
        });

        jrdelete.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrdelete);
        jrdelete.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jrdelete.setForeground(new java.awt.Color(255, 255, 255));
        jrdelete.setText("Delete Employ");
        jrdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioquit)
                    .addComponent(radioshow)
                    .addComponent(radiosearch)
                    .addComponent(radioadd)
                    .addComponent(jLabel1)
                    .addComponent(jbupdate))
                .addGap(0, 120, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioadd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radiosearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioshow, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrdelete, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioquit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioaddActionPerformed
        if (radioadd.isSelected());
        {
            AddEmp addemp = new AddEmp();
            addemp.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_radioaddActionPerformed

    private void radiosearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiosearchActionPerformed
        if (radiosearch.isSelected());
        {
            SearchEmp searchemp = new SearchEmp();
            searchemp.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_radiosearchActionPerformed

    private void radioshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioshowActionPerformed
        if (radioshow.isSelected()) {
            DetailsEmp showemp = new DetailsEmp();
            showemp.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_radioshowActionPerformed

    private void radioquitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioquitActionPerformed
        if (radioquit.isSelected()) {
            int answer = JOptionPane.showConfirmDialog(null, "Are you sure you want to quit", "Quiting", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (answer == JOptionPane.YES_OPTION) {
                DBConnection.closeConnection();
                JOptionPane.showMessageDialog(null, "Thankyou for using the app!");
                System.exit(0);

            }

        }
    }//GEN-LAST:event_radioquitActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        setOpacity((float)0.8);
        xx = evt.getX();
        xy= evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
        setOpacity(1);
        
    }//GEN-LAST:event_formMouseReleased

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged

        // TODO add your handling code here:
         int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx,y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void jrdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdeleteActionPerformed
        // TODO add your handling code here:
        deleteEmploye obj = new deleteEmploye();
        this.dispose();
        obj.setVisible(true); 
    }//GEN-LAST:event_jrdeleteActionPerformed

    private void jbupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbupdateActionPerformed
       if(jbupdate.isSelected())
       {
           updateDetails obj = new updateDetails();
           this.dispose();
           obj.setVisible(true);
       }
    }//GEN-LAST:event_jbupdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChoiceEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChoiceEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChoiceEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChoiceEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChoiceEmp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jbupdate;
    private javax.swing.JRadioButton jrdelete;
    private javax.swing.JRadioButton radioadd;
    private javax.swing.JRadioButton radioquit;
    private javax.swing.JRadioButton radiosearch;
    private javax.swing.JRadioButton radioshow;
    // End of variables declaration//GEN-END:variables
}
